[workspace]

members = [
    "raspi3_boot",
    "bcm2837",
    "mailbox",
    "display",
    "gui",
    "fb-test-project",
    "eg-test-project",
    "display-mbox-props",
    "clock-display",
    "graphics-test-project",
]
