[package]
name = "raspi3_boot"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]

[dependencies]
r0 = "0.2.2"

[dependencies.panic-abort]
version = "0.3.1"
optional = true

[features]
default = ["panic-and-abort"]
panic-and-abort = ["panic-abort"]
